---
name: Build SFML Puzzle Game
'on':
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Cache vcpkg for Windows
      - name: Cache vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v3
        with: 
          path: |
            ${{ github.workspace}}/vcpkg
            !${{ github.workspace}}/vcpkg/buildtrees
            !${{ github.workspace }}/vcpkg/packages
            !${{ github.workspace }}/vcpkg/downloads

          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json')}}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

  
      # Setup vcpkg for Windows
      - name: Setup vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if (-not (Test-Path vcpkg/.git)) {
            git clone --depth 1 --branch master https://github.com/microsoft/vcpkg.git
          }
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
        shell: pwsh


        # Setup dependencies for Windows
      - name: Install dependencies  (Windows)
        if: matrix.os == 'windows-latest'
        run: .\vcpkg\vcpkg install sdl2 sdl2-image sdl2-ttf --triplet x64-windows
        shell: pwsh

      # macOS dependencies via Homebrew
      - name: Install SFML (MacOS)
        if: matrix.os == 'macos-latest'
        run: brew install sfml

      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      - name: Configure Cmake (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -B build -S . `
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/builtin/vcpkg.cmake"
        shell: pwsh

      - name: Configure CMake (macOS)
        if: matrix.os == 'macos-latest'
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
  
      # Build
      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}}   

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
    # See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml